import React, { useState } from 'react';
import styles from './Faq.module.css';

function FAQ() {
  const [activeIndex, setActiveIndex] = useState(null);

  const questions = [
    {
      question: 'What are' + ' {/* Placeholder for Project Name */}',
      answer: ' {/* Placeholder for Project Name */} ' + ' are a collection of ' + ' {/* Placeholder for Supply */} ' + ' unique NFTs on the ' + ' {/* Placeholder for Blockchain */} ' + ' blockchain. Each' + ' {/* Placeholder for Project Name */} ' + 'is a unique piece of art generated by an algorithm. The' + ' {/* Placeholder for Project Name */} ' + 'are inspired by' + ' {/* Placeholder for Project Name */} ' + 'and are a homage to the' + ' {/* Placeholder for Project Name */} ' + 'of the past. The' + ' {/* Placeholder for Project Name */} ' + 'are generated from a collection of hand drawn parts and are randomized and stored on chain.',
    },
    {
      question: 'How can I purchase' + ' {/* Placeholder for Project Name */} ',
      answer: 'Once the' + ' {/* Placeholder for Project Name */} ' + 'are available for sale, you will be able to purchase them on the designated marketplace. Stay tuned for more information on the launch date and marketplace on our official channels.',
    },
    {
      question: 'How much do' + ' {/* Placeholder for Project Name */} ' + 'cost?',
      answer: 'Pricing information will be announced closer to the sale date. Please kep an eye on our official channels for more information.',
    },
    {
      question: 'How many ' + ' {/* Placeholder for Project Name */} ' + 'will be minted?',
      answer: 'There are a total of ' + '{/* Placeholder for Supply */} ' + ' {/* Placeholder for Project Name */} ' + 'that will be minted.',
    },
    {
      question: 'What blockchain will' + ' {/* Placeholder for Project Name */} ' + 'be on?',
      answer: ' {/* Placeholder for Project Name */} ' + 'will be on the ' + ' {/* Placeholder for Blockchain */} ' + 'blockchain.',
    },
  ];

  const handleToggle = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <div id="Faq" className={styles.container}>
      <h2 className={styles.title}>FAQ</h2>
      <div className={styles.box}>
        {questions.map((item, index) => (
          <div key={index} className={styles.questionContainer}>
            <div
              className={`${styles.question} ${activeIndex === index ? styles.active : ''}`}
              onClick={() => handleToggle(index)}
            >
              <span>{item.question}</span>
              <div className={`${styles.arrowIcon} ${activeIndex === index ? styles.rotated : ''}`}>&#9660;</div>
            </div>
            <div className={`${styles.answerContainer} ${activeIndex === index ? styles.expanded : ''}`}>
              <p className={styles.answer}>{item.answer}</p>
            </div>
            {index !== questions.length && <hr className={`${styles.line} ${activeIndex === index ? styles.expandedLine : ''}`} />}
          </div>
        ))}
      </div>
    </div>
  );
}

export default FAQ;
